template:
  path: access-secret-policy.yaml
stack_name: iatlas-access-secret-policy-prod
stack_tags: {{stack_group_config.stack_tags}}
parameters:
  DbCredsSecretName: 'iatlas_db_creds_encrypted_prod'
  GitLabContainerSecretName: 'gitlab_registry_creds_prod'
