template_path: gitlab-manager-runner-roles.yaml
stack_name: iatlas-gitlab-roles-prod
dependencies:
  - common/iatlasvpc.yaml
  - prod/iatlas-runner-s3-bucket.yaml
  - prod/iatlas-access-secret-policy.yaml
stack_tags: {{stack_group_config.stack_tags}}
parameters:
  AccessSecretPolicyArn: !stack_output_external iatlas-access-secret-policy-prod::AccessSecretPolicyArn
  VpcId: !stack_output_external iatlasvpc::VPCId
  EcsClusterName: {{stack_group_config.ecs_cluster_name_prod}}
  EcsServiceName: {{stack_group_config.ecs_service_name_prod}}
  GitLabRunnerInstanceType: {{stack_group_config.gitlab_runner_instance_type_prod}}
  CacheBucketArn: !stack_output_external iatlas-gitlab-s3-bucket-prod::CacheBucketArn
