template_path: ecs-roles.yaml
stack_name: iatlas-api-roles-staging
dependencies:
  - staging/iatlas-access-secret-policy.yaml
stack_tags: {{stack_group_config.stack_tags}}
parameters:
  AccessSecretPolicyArn: !stack_output_external iatlas-access-secret-policy-staging::AccessSecretPolicyArn
