template_path: runner.yaml
stack_name: iatlas-runner
dependencies:
  - common/iatlas.yaml
parameters:
  Department: "CompOnc"
  Project: "iAtlas"
  OwnerEmail: "andrew.lamb@sagebase.org"
  InstanceType: "t2.nano"
  VpcName: iatlasvpc
  VpcSubnet: PrivateSubnet
  AMIId: ami-0810a318c4b1243c5 #AWS Linux from https://ami.sageit.org
