template_path: remote/vpc-mini.yaml
stack_name: iatlas-vpc
parameters:
  VpcSubnetPrefix: "10.255.20"
  VpcName: iatlas-vpc
hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/master/vpc-mini.yaml --create-dirs -o templates/remote/vpc-mini.yaml"
