template_path: gitlab-manager-runner.yaml
stack_name: iatlas-gitlab-manager
dependencies:
  - common/iatlasvpc.yaml
  - prod/iatlas-db.yaml
  - prod/iatlas-kms.yaml
  - staging/iatlas-db.yaml
  - staging/iatlas-kms.yaml
stack_tags: {{stack_group_config.stack_tags}}
parameters:
  VpcId: !stack_output_external iatlasvpc::VPCId
  PrivateSubnetIds:
    - !stack_output_external iatlasvpc::PrivateSubnet
    - !stack_output_external iatlasvpc::PrivateSubnet1
    - !stack_output_external iatlasvpc::PrivateSubnet2
  KeyName: 'iatlas-gitlab-runner'
  DbHostProd: !stack_output_external iatlasdb-prod::ClusterEndpoint
  DbHostStaging: !stack_output_external iatlasdb-staging::ClusterEndpoint
  DbPortProd: !stack_output_external iatlasdb-prod::ClusterPort
  DbPortStaging: !stack_output_external iatlasdb-staging::ClusterPort
  DbCredsSecretProd: !stack_output_external iatlasdb-prod::DbCredsName
  DbCredsSecretStaging: !stack_output_external iatlasdb-staging::DbCredsName
  DBAccessSecurityGroupNameProd: !stack_output_external iatlasdb-prod::DBAccessSecurityGroupName
  DBAccessSecurityGroupNameStaging: !stack_output_external iatlasdb-staging::DBAccessSecurityGroupName
  KmsKeyArnProd: !stack_output_external iatlas-kms-prod::KmsKeyArn
  KmsKeyArnStaging: !stack_output_external iatlas-kms-staging::KmsKeyArn
  GitLabRegToken: {{stack_group_config.gitlab_reg_token}}
  GitLabRunnerInstanceType: 'c5d.2xlarge'
on_failure: 'DO_NOTHING'
