template:
  type: http
  url: https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.2.20/R53-hostedzone.yaml
stack_name: iatlas-dns-zone
stack_tags: {{stack_group_config.stack_tags}}
parameters:
  Department: {{stack_group_config.stack_tags.Department}}
  Project: {{stack_group_config.stack_tags.Project}}
  OwnerEmail: {{stack_group_config.stack_tags.OwnerEmail}}
  DnsDomainName: {{stack_group_config.domain_name}}
