AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DbCredsSecretName:
    Description: The name of the DB Secret.
    Type: String
  GitLabContainerSecretName:
    Description: Name of the secret that holds the credentials for accessing the GitLab container registry.
    Type: String

Resources:
  ########################
  ### Managed Policies ###
  ########################
  AccessSecretPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - kms:Decrypt
            Resource:
              - !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*'
              - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DbCredsSecretName}-??????'
              - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GitLabContainerSecretName}-??????'
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'

Outputs:
  StackName:
    Value: !Ref 'AWS::StackName'
  AccessSecretPolicyArn:
    Description: The Access Secret Policy.
    Value: !Ref 'AccessSecretPolicy'
