# Setting up a certificate requires a manual step to enter the DNS Validation on the registrar.
Description: Setup an ACM Certificate
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html#cfn-certificatemanager-certificate-domainname
  DnsDomainName:
    Description: Domain to secure with the certificate (i.e. sagebionetworks.org)
    Type: String
  DnsSubDomainName:
    Description: Sub domain (default is '*') to secure with certificate (i.e. "api" of api.cri-iatlas.org)
    Type: String
    Default: '*'
  HostedZoneId:
    Description: The id of the Hosted Zone
    Type: String
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '${DnsSubDomainName}.${DnsDomainName}'
      DomainValidationOptions:
        - DomainName: !Sub '${DnsSubDomainName}.${DnsDomainName}'
          HostedZoneId: !Ref 'HostedZoneId'
      ValidationMethod: 'DNS'
      Tags:
        - Key: 'Name'
          Value: !Ref AWS::StackName
Outputs:
  CertificateArn:
    Value: !Ref Certificate
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-CertificateArn'
