AWSTemplateFormatVersion: 2010-09-09
Description: >-
  A worker host for a GitLab runner connected to Jumpcloud
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t3.nano
  InstanceName:
    Type: String
    Description: The name to be applied to the EC2 instance so that it may be more easily identified in the console.
  VpcSubnet:
    Description: Existing VPC subnet to home the instance. Currently only private subnets allowed.
    Type: String
    Default: PrivateSubnet
    AllowedValues:
      - PrivateSubnet
      - PrivateSubnet1
      - PrivateSubnet2
  VpcName:
    Description: Name of an existing VPC to run the instance in.
    Type: String
    Default: iatlasvpc
  # See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/retrieve-ecs-optimized_AMI.html
  LatestEcsAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id'
    Description: A reference to the latest ECS Optimized AMI Id.
  Environment:
    Description: Indication of which environment this runner is associated with
    Type: String

Resources:
  # Managed Policies:

  # KMS Keys
  KmsDecryptManagedPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ReadAccess
            Action:
              - 'kms:ListKeys'
              - 'kms:ListAliases'
              - 'kms:DescribeKey'
              - 'kms:ListKeyPolicies'
              - 'kms:GetKeyPolicy'
              - 'kms:GetKeyRotationStatus'
              - 'iam:ListUsers'
              - 'iam:ListRoles'
            Effect: Allow
            Resource: !ImportValue
              'Fn::Sub': '${AWS::Region}-iatlas-kms-${Environment}-KmsKeyArn'
          - Sid: DecryptAccess
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
            Effect: Allow
            Resource: !ImportValue
              'Fn::Sub': '${AWS::Region}-iatlas-kms-${Environment}-KmsKeyArn'
  # Allow read parameter on arn...parameter/iatlas/{prod,staging}/*
  SsmManagedPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: GetParamAccess
            Action:
              - 'ssm:*'
            Effect: Allow
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/iatlas/${Environment}/*'

  # Roles

  EC2ServiceRole: # TODO will need to add roles for snapshotting DB
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - ssm.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-essentials-TagRootVolumePolicy'
        - !Ref SsmManagedPolicy
        - !Ref KmsDecryptManagedPolicy
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'

  # Profiles

  RunnerInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: '/'
      Roles:
        - !Ref EC2ServiceRole

  RunnerEc2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref 'LatestEcsAmiId'
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref RunnerInstanceProfile
      NetworkInterfaces:
        - DeleteOnTermination: true
          DeviceIndex: '0'
          GroupSet:
            - !ImportValue
              'Fn::Sub': '${AWS::Region}-${VpcName}-VpnSecurityGroup'
            - !ImportValue
              'Fn::Sub': '${AWS::Region}-iatlasdb-${Environment}-DBAccessSecurityGroup'
          SubnetId: !ImportValue
            'Fn::Sub': '${AWS::Region}-${VpcName}-${VpcSubnet}'
      Tags:
        - Key: 'Name'
          Value: !Ref 'InstanceName'
        - Key: 'ManagedInstanceMaintenanceTarget'
          Value: 'yes'
        - Key: 'PatchGroup'
          Value: 'prod-default'
Outputs:
  RunnerEc2InstanceId:
    Value: !Ref RunnerEc2Instance
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-Ec2InstanceId'
