# This creates a common set of resources of iAtlas.
AWSTemplateFormatVersion: 2010-09-09
Description: KMS Keys for iAtlas
Parameters:
  KeyAdminArns:
    Type: CommaDelimitedList
    Description: A list of principals ARNs that can administrate the KMS key
    ConstraintDescription: List of ARNs (i.e. ["arn:aws:iam::123456789:root", "arn:aws:iam::987654321:jsmith"]
  KeyUserArns:
    Type: CommaDelimitedList
    Description: A list of principals ARNs that can access the KMS key
    ConstraintDescription: List of ARNs (i.e. ["arn:aws:iam::123456789:root", "arn:aws:iam::987654321:jsmith"]
Resources:
  KmsKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: !Sub '${AWS::StackName}-KmsKey'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          -
            Sid: 'Allow administration of the key'
            Effect: 'Allow'
            Principal:
              AWS: !Ref KeyAdminArns
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          -
            Sid: 'Allow use of the key'
            Effect: 'Allow'
            Principal:
              AWS: !Ref KeyUserArns
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
  KmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/${AWS::StackName}/KmsKey'
      TargetKeyId: !Ref KmsKey
Outputs:
  KmsKey:
    Value: !Ref KmsKey
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-KmsKey'
  KmsKeyAlias:
    Value: !Ref KmsKeyAlias
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-KmsKeyAlias'
  KmsKeyArn:
    Value: !GetAtt KmsKey.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-KmsKeyArn'
