Description: Setup a hosted zone for DNS
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SubDomainName:
    Default: '*'
    Description: Sub domain (default is '*') for the hostedzone (i.e. "api" of api.cri-iatlas.org)
    Type: String
  DomainName:
    Description: The domain name (i.e. sagebionetworks.org)
    Type: String
Resources:
  HostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      HostedZoneConfig:
        Comment: !Sub 'Hosted zone for ${SubDomainName}.${DomainName}'
      Name: !Sub '${SubDomainName}.${DomainName}'
      HostedZoneTags:
        - Key: 'Name'
          Value: !Ref AWS::StackName
Outputs:
  HostedZoneId:
    Value: !Ref HostedZone
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-HostedZoneId'
